### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by chris-sekira**
Updated Official Pretzel Brand

### CODE REVIEW

**Comment by benjaminrlawrence** [comment]
Should be a comma between "Dark" and "Extra". Please revise.

**Comment by chris-sekira** [comment]
> Should be a comma between "Dark" and "Extra". Please revise.

This comment is "Extra" bullshit!

**Comment by fleapower** [comment]
Unrelated question...did you ever figure out how to receive multi-recipient MMS's through Pulse on your Nokia 6.1?

**Comment by chris-sekira** [comment]
LMAO!

Nope, I just switched to the Google Messages app and never looked back. I still wish Pulse would work, but oh well.

**Pull request merged**
